#!/bin/sh
case "$1" in
	"c")      xclip -in -filter | tr '\n' ' ' | xclip -in -selection clipboard ;;	
	"x")      dragon-drag-and-drop -x -I ;;
	"m")      read path && mpv $path ;;
	"w")      read path && cp -lf $path ~/img/wallpapers/.current-wall && feh --bg-fill ~/img/wallpapers/.current-wall --no-fehbg ;;
esac
