#!/bin/sh

userresources=~/.config/X11/Xresources
usermodmap=~/.config/X11/Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

[ -f $sysresources ] && xrdb -merge "$sysresources"
[ -f $sysmodmap ] && xmodmap "$sysmodmap"
[ -f "$userresources" ] && xrdb -merge "$userresources"
[ -f "$usermodmap" ] && xmodmap "$usermodmap"

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

picom --experimental-backends -b &
xset r rate 250 50 &
xsetwacom --set "Wacom Intuos Pro M Pen stylus" MapToOutput HEAD-0 &
setxkbmap -option caps:swapescape &
feh --bg-fill ~/img/wallpapers/.current-wall --no-fehbg &
exec bspwm
