#! /bin/sh

xsetroot -cursor_name left_ptr
launch-polybar.sh
pgrep -x sxhkd > /dev/null || sxhkd &
pgrep bspswallow || bspswallow &

bspc monitor DP-0 -d 1 2 3 4 5
bspc monitor DP-4 -d 1 2 3 4 5

bspc config border_width       	2
bspc config window_gap          12

bspc config normal_border_color  "#4D4D4D"
bspc config active_border_color  "#BD93F9"
bspc config focused_border_color "#CAA9FA"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       true

bspc config pointer_motion_interval 7

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
